import type { Metadata } from 'next';
import { NavigationBar } from '@/components/ui/';

import { Fredoka } from 'next/font/google';

import { ThemeProvider } from './providers'

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface RootLayouProps {
  children: React.ReactNode;
}

const fredoka = Fredoka({ subsets: ['latin'], variable: '--fredoka' });

const RootLayout = ({ children }: RootLayouProps) => {
  return (
    <html lang='en'>
      <body
        className={`h-screen w-screen bg-slate-100 dark:bg-zinc-950 ${fredoka.variable} font-sans`}
      >
        <ThemeProvider>
          <NavigationBar></NavigationBar>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
